**Тема «POS-tagger и NER»**

Задание 1.

Написать теггер на данных с русским языком:
1. проверить UnigramTagger, BigramTagger, TrigramTagger и их комбинации;
2. написать свой теггер как на занятии, попробовать разные векторайзеры, добавить знание не только букв, но и слов;
3. сравнить все реализованные методы, сделать выводы.


Задание 2.

Проверить, насколько хорошо работает NER
(Данные брать из Index of /pub/named_entities):
1. проверить NER из nltk/spacy/deeppavlov;
2. написать свой NER, попробовать разные подходы.

1) передаём в сетку токен и его соседей.

2) передаём в сетку только токен.

3) свой вариант.
3. сравнить свои реализованные подходы на качество — вывести precision/recall/f1_score.

In [1]:
from google.colab import drive
drive.mount('./drive')

Drive already mounted at ./drive; to attempt to forcibly remount, call drive.mount("./drive", force_remount=True).

In [2]:
!pip -q install pyconll
!pip -q install corus
!pip -q install -U spacy
!pip3 -q install deeppavlov

In [3]:
!wget -O ru_syntagrus-ud-train.conllu https://raw.githubusercontent.com/UniversalDependencies/UD_Russian-SynTagRus/master/ru_syntagrus-ud-train-a.conllu
!wget -O ru_syntagrus-ud-dev.conllu https://raw.githubusercontent.com/UniversalDependencies/UD_Russian-SynTagRus/master/ru_syntagrus-ud-dev.conllu

--2023-12-04 19:15:18--  https://raw.githubusercontent.com/UniversalDependencies/UD_Russian-SynTagRus/master/ru_syntagrus-ud-train-a.conllu
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 40736599 (39M) [text/plain]
Saving to: ‘ru_syntagrus-ud-train.conllu’

ru_syntagrus-ud-tra 100%[===================>]  38.85M   191MB/s    in 0.2s

2023-12-04 19:15:19 (191 MB/s) - ‘ru_syntagrus-ud-train.conllu’ saved [40736599/40736599]

--2023-12-04 19:15:19--  https://raw.githubusercontent.com/UniversalDependencies/UD_Russian-SynTagRus/master/ru_syntagrus-ud-dev.conllu
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 14704579 (14M) [text/plain]
Saving to: ‘ru_syntagrus-ud-dev.conllu’

ru_syntagrus-ud-dev 100%[===================>]  14.02M  --.-KB/s    in 0.1s

2023-12-04 19:15:19 (109 MB/s) - ‘ru_syntagrus-ud-dev.conllu’ saved [14704579/14704579]

In [56]:
import pandas as pd
import numpy as np
import re

from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.feature_extraction.text import CountVectorizer, HashingVectorizer, TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, f1_score, classification_report
from sklearn import model_selection, preprocessing, linear_model

import pyconll
import nltk
from nltk.tag import DefaultTagger, UnigramTagger, BigramTagger, TrigramTagger, RegexpTagger
from nltk.tokenize import word_tokenize

import corus
from corus import load_ne5

import spacy
from spacy import displacy
import ru_core_news_sm
from spacy.lang.ru.examples import sentences
from spacy.lang.ru import Russian

import tensorflow as tf
from keras import Sequential
from keras.layers import Dense, Embedding, GlobalAveragePooling1D
from keras.layers import GlobalMaxPooling1D, Conv1D, GRU, LSTM, Dropout, Input
from keras.layers.experimental.preprocessing import TextVectorization

from razdel import tokenize
from corus import load_ne5

from razdel import tokenize
from corus import load_ne5

import matplotlib
%matplotlib inline

import warnings
warnings.filterwarnings('ignore')

In [6]:
data_train = pyconll.load_from_file('/content/drive/MyDrive/NLP/ru_syntagrus-ud-train.conllu')
data_test = pyconll.load_from_file('/content/drive/MyDrive/NLP/ru_syntagrus-ud-dev.conllu')

In [7]:
fdata_train = []
for sent in data_train[:]:
    fdata_train.append([(token.form, token.upos) for token in sent])

fdata_test = []
for sent in data_test[:]:
    fdata_test.append([(token.form, token.upos) for token in sent])

fdata_sent_test = []
for sent in data_test[:]:
    fdata_sent_test.append([token.form for token in sent])

In [8]:
len(fdata_train), len(fdata_test), len(fdata_sent_test)

(24516, 8906, 8906)

In [9]:
fdata_train[:2]

[[('Анкета', 'NOUN'), ('.', 'PUNCT')],
 [('Начальник', 'NOUN'),
  ('областного', 'ADJ'),
  ('управления', 'NOUN'),
  ('связи', 'NOUN'),
  ('Семен', 'PROPN'),
  ('Еремеевич', 'PROPN'),
  ('был', 'AUX'),
  ('человек', 'NOUN'),
  ('простой', 'ADJ'),
  (',', 'PUNCT'),
  ('приходил', 'VERB'),
  ('на', 'ADP'),
  ('работу', 'NOUN'),
  ('всегда', 'ADV'),
  ('вовремя', 'ADV'),
  (',', 'PUNCT'),
  ('здоровался', 'VERB'),
  ('с', 'ADP'),
  ('секретаршей', 'NOUN'),
  ('за', 'ADP'),
  ('руку', 'NOUN'),
  ('и', 'CCONJ'),
  ('иногда', 'ADV'),
  ('даже', 'PART'),
  ('писал', 'VERB'),
  ('в', 'ADP'),
  ('стенгазету', 'NOUN'),
  ('заметки', 'NOUN'),
  ('под', 'ADP'),
  ('псевдонимом', 'NOUN'),
  ('"', 'PUNCT'),
  ('Муха', 'NOUN'),
  ('"', 'PUNCT'),
  ('.', 'PUNCT')]]

In [11]:
default_tagger = nltk.DefaultTagger('NN')
default_acc = default_tagger.evaluate(fdata_test)

unigram_tagger = UnigramTagger(fdata_train)
unigram_acc = unigram_tagger.evaluate(fdata_test)

bigram_tagger = BigramTagger(fdata_train)
bigram_acc = bigram_tagger.evaluate(fdata_test)

trigram_tagger = TrigramTagger(fdata_train)
trigram_acc = trigram_tagger.evaluate(fdata_test)

bigram_tagger = BigramTagger(fdata_train, backoff=unigram_tagger)
bigram_unigram_acc = bigram_tagger.evaluate(fdata_test)

trigram_tagger = TrigramTagger(fdata_train, backoff=bigram_tagger)
trigram_bigram_unigram_acc = trigram_tagger.evaluate(fdata_test)

print(f'Accuracy:\nDefault Tagger: {round(default_acc, 3)},\nUnigram Tagger: {round(unigram_acc, 3)},\nBigram Tagger: {round(bigram_acc, 5)},\n'
      f'Trigram Tagger: {round(trigram_acc, 3)},\nBigram and Unigram Tagger: {round(bigram_unigram_acc, 5)},\n'
      f'Trigram, Bigram and Unigram Tagger: {round(trigram_bigram_unigram_acc, 5)},\n')

Accuracy:
Default Tagger: 0.0,
Unigram Tagger: 0.824,
Bigram Tagger: 0.60939,
Trigram Tagger: 0.178,
Bigram and Unigram Tagger: 0.82928,
Trigram, Bigram and Unigram Tagger: 0.82914,

Различные комбинации теггеров могут давать прирост качества.

Попробуем объединить работу всех теггеров с помощью функции.

In [12]:
def union_taggers(train_sents, tagger_classes, backoff=None):
    for cls in tagger_classes:
        backoff = cls(train_sents, backoff=backoff)
    return backoff


backoff = DefaultTagger('NN')
tag = union_taggers(fdata_train,
                     [UnigramTagger, BigramTagger, TrigramTagger],
                     backoff = backoff)

tag.evaluate(fdata_test)

0.827905462595221

Получили усредненный результат. Не самый высокий.

Преобразуем тренировочный датасет в списки слов и списки POS-разметки.

In [14]:
train_tok = []
train_label = []
for sent in fdata_train[:]:
    for tok in sent:
        train_tok.append(tok[0])
        train_label.append('NO_TAG' if tok[1] is None else tok[1])

test_tok = []
test_label = []
for sent in fdata_test[:]:
    for tok in sent:
        test_tok.append(' ' if tok[0] is None else tok[0])
        test_label.append('NO_TAG' if tok[1] is None else tok[1])

In [15]:
train_tok[:7], train_label[:7]

(['Анкета', '.', 'Начальник', 'областного', 'управления', 'связи', 'Семен'],
 ['NOUN', 'PUNCT', 'NOUN', 'ADJ', 'NOUN', 'NOUN', 'PROPN'])

In [16]:
le = LabelEncoder()
train_enc_labels = le.fit_transform(train_label)
train_enc_labels

array([ 7, 13,  7, ...,  1, 11, 13])

In [17]:
test_enc_labels = le.transform(test_label)
test_enc_labels

array([ 7, 13,  1, ...,  0,  7, 13])

In [18]:
le.classes_

array(['ADJ', 'ADP', 'ADV', 'AUX', 'CCONJ', 'DET', 'INTJ', 'NOUN',
       'NO_TAG', 'NUM', 'PART', 'PRON', 'PROPN', 'PUNCT', 'SCONJ', 'SYM',
       'VERB', 'X'], dtype='<U6')

In [19]:
%time

vectorizers = [CountVectorizer(ngram_range=(1, 5), analyzer='char'),
               TfidfVectorizer(ngram_range=(1, 5), analyzer='char'),
               HashingVectorizer(ngram_range=(1, 5), analyzer='char', n_features=1000)]
vectorizers_word = [CountVectorizer(ngram_range=(1, 5), analyzer='word'),
               TfidfVectorizer(ngram_range=(1, 5), analyzer='word'),
               HashingVectorizer(ngram_range=(1, 5), analyzer='word', n_features=1000)]
n_features = [2000, 3000, 5000]
vectorizers_hash = [HashingVectorizer(ngram_range=(1, 5), analyzer='char', n_features=feat) for feat in n_features]
vectorizers_hash_word = [HashingVectorizer(ngram_range=(1, 5), analyzer='word', n_features=feat) for feat in n_features]
f1_scores = []
accuracy_scores = []

for vectorizer in vectorizers + vectorizers_word + vectorizers_hash + vectorizers_hash_word:
    X_train = vectorizer.fit_transform(train_tok)
    X_test = vectorizer.transform(test_tok)

    lr = LogisticRegression(random_state=0, max_iter=100)
    lr.fit(X_train, train_enc_labels)
    pred = lr.predict(X_test)
    f1 = f1_score(test_enc_labels, pred, average='weighted')
    f1_scores.append(f1)
    acc = accuracy_score(test_enc_labels, pred)
    accuracy_scores.append(acc)

    print(vectorizer)
    print(classification_report(test_enc_labels, pred, target_names=le.classes_))

CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 8.11 µs
CountVectorizer(analyzer='char', ngram_range=(1, 5))
              precision    recall  f1-score   support

         ADJ       0.93      0.93      0.93     15103
         ADP       0.98      1.00      0.99     13717
         ADV       0.92      0.92      0.92      7783
         AUX       0.82      0.96      0.88      1390
       CCONJ       0.89      0.97      0.93      5672
         DET       0.89      0.70      0.79      4265
        INTJ       0.39      0.29      0.33        24
        NOUN       0.94      0.97      0.96     36238
      NO_TAG       1.00      0.77      0.87       265
         NUM       0.86      0.91      0.88      1734
        PART       0.95      0.77      0.85      5125
        PRON       0.86      0.89      0.87      7444
       PROPN       0.83      0.66      0.74      5473
       PUNCT       1.00      1.00      1.00     29186
       SCONJ       0.75      0.97      0.85      2865
         SYM       1.00      0.85      0.92        62
        VERB       0.97      0.95      0.96     17110
           X       0.58      0.08      0.14       134

    accuracy                           0.94    153590
   macro avg       0.86      0.81      0.82    153590
weighted avg       0.94      0.94      0.94    153590

TfidfVectorizer(analyzer='char', ngram_range=(1, 5))
              precision    recall  f1-score   support

         ADJ       0.91      0.91      0.91     15103
         ADP       0.99      1.00      1.00     13717
         ADV       0.92      0.87      0.90      7783
         AUX       0.82      0.97      0.89      1390
       CCONJ       0.89      0.97      0.93      5672
         DET       0.89      0.70      0.78      4265
        INTJ       0.00      0.00      0.00        24
        NOUN       0.90      0.97      0.94     36238
      NO_TAG       1.00      0.77      0.87       265
         NUM       0.85      0.89      0.87      1734
        PART       0.93      0.78      0.85      5125
        PRON       0.84      0.91      0.87      7444
       PROPN       0.84      0.49      0.62      5473
       PUNCT       1.00      1.00      1.00     29186
       SCONJ       0.81      0.88      0.84      2865
         SYM       1.00      0.69      0.82        62
        VERB       0.93      0.94      0.94     17110
           X       0.34      0.09      0.14       134

    accuracy                           0.93    153590
   macro avg       0.83      0.77      0.79    153590
weighted avg       0.93      0.93      0.92    153590

HashingVectorizer(analyzer='char', n_features=1000, ngram_range=(1, 5))
              precision    recall  f1-score   support

         ADJ       0.82      0.78      0.80     15103
         ADP       0.97      0.99      0.98     13717
         ADV       0.83      0.77      0.80      7783
         AUX       0.81      0.96      0.88      1390
       CCONJ       0.89      0.97      0.93      5672
         DET       0.85      0.73      0.79      4265
        INTJ       0.00      0.00      0.00        24
        NOUN       0.80      0.89      0.84     36238
      NO_TAG       1.00      0.77      0.87       265
         NUM       0.80      0.80      0.80      1734
        PART       0.92      0.76      0.83      5125
        PRON       0.81      0.88      0.85      7444
       PROPN       0.65      0.38      0.48      5473
       PUNCT       1.00      1.00      1.00     29186
       SCONJ       0.80      0.90      0.85      2865
         SYM       1.00      0.69      0.82        62
        VERB       0.85      0.80      0.83     17110
           X       0.00      0.00      0.00       134

    accuracy                           0.87    153590
   macro avg       0.77      0.73      0.74    153590
weighted avg       0.87      0.87      0.86    153590

CountVectorizer(ngram_range=(1, 5))
              precision    recall  f1-score   support

         ADJ       0.94      0.37      0.54     15103
         ADP       0.99      0.48      0.64     13717
         ADV       0.94      0.78      0.85      7783
         AUX       0.82      0.95      0.88      1390
       CCONJ       0.95      0.19      0.31      5672
         DET       0.81      0.72      0.76      4265
        INTJ       0.00      0.00      0.00        24
        NOUN       0.98      0.61      0.75     36238
      NO_TAG       0.00      0.00      0.00       265
         NUM       0.86      0.63      0.73      1734
        PART       0.94      0.76      0.84      5125
        PRON       0.91      0.75      0.82      7444
       PROPN       0.90      0.15      0.25      5473
       PUNCT       0.36      1.00      0.53     29186
       SCONJ       0.74      0.94      0.83      2865
         SYM       0.00      0.00      0.00        62
        VERB       0.98      0.43      0.60     17110
           X       0.00      0.00      0.00       134

    accuracy                           0.63    153590
   macro avg       0.67      0.49      0.52    153590
weighted avg       0.83      0.63      0.64    153590

TfidfVectorizer(ngram_range=(1, 5))
              precision    recall  f1-score   support

         ADJ       0.93      0.41      0.57     15103
         ADP       0.99      0.48      0.64     13717
         ADV       0.94      0.77      0.85      7783
         AUX       0.84      0.87      0.85      1390
       CCONJ       0.88      0.20      0.33      5672
         DET       0.83      0.71      0.76      4265
        INTJ       0.00      0.00      0.00        24
        NOUN       0.98      0.65      0.78     36238
      NO_TAG       0.00      0.00      0.00       265
         NUM       0.88      0.55      0.68      1734
        PART       0.97      0.73      0.83      5125
        PRON       0.87      0.77      0.81      7444
       PROPN       0.93      0.15      0.25      5473
       PUNCT       0.37      1.00      0.54     29186
       SCONJ       0.70      0.92      0.79      2865
         SYM       0.00      0.00      0.00        62
        VERB       0.97      0.44      0.60     17110
           X       0.00      0.00      0.00       134

    accuracy                           0.64    153590
   macro avg       0.67      0.48      0.52    153590
weighted avg       0.83      0.64      0.65    153590

HashingVectorizer(n_features=1000, ngram_range=(1, 5))
              precision    recall  f1-score   support

         ADJ       0.41      0.20      0.27     15103
         ADP       0.83      0.47      0.60     13717
         ADV       0.55      0.62      0.59      7783
         AUX       0.70      0.94      0.80      1390
       CCONJ       0.88      0.18      0.29      5672
         DET       0.50      0.56      0.53      4265
        INTJ       0.00      0.00      0.00        24
        NOUN       0.25      0.53      0.34     36238
      NO_TAG       0.00      0.00      0.00       265
         NUM       0.38      0.46      0.42      1734
        PART       0.82      0.75      0.78      5125
        PRON       0.65      0.74      0.69      7444
       PROPN       0.29      0.08      0.12      5473
       PUNCT       0.00      0.00      0.00     29186
       SCONJ       0.72      0.87      0.78      2865
         SYM       0.00      0.00      0.00        62
        VERB       0.46      0.24      0.32     17110
           X       0.00      0.00      0.00       134

    accuracy                           0.36    153590
   macro avg       0.41      0.37      0.36    153590
weighted avg       0.39      0.36      0.34    153590

HashingVectorizer(analyzer='char', n_features=2000, ngram_range=(1, 5))
              precision    recall  f1-score   support

         ADJ       0.86      0.86      0.86     15103
         ADP       0.98      0.99      0.98     13717
         ADV       0.87      0.82      0.84      7783
         AUX       0.81      0.97      0.88      1390
       CCONJ       0.89      0.97      0.93      5672
         DET       0.87      0.72      0.79      4265
        INTJ       0.00      0.00      0.00        24
        NOUN       0.85      0.93      0.89     36238
      NO_TAG       1.00      0.77      0.87       265
         NUM       0.82      0.84      0.83      1734
        PART       0.93      0.78      0.84      5125
        PRON       0.82      0.90      0.86      7444
       PROPN       0.70      0.41      0.52      5473
       PUNCT       1.00      1.00      1.00     29186
       SCONJ       0.81      0.90      0.85      2865
         SYM       1.00      0.69      0.82        62
        VERB       0.90      0.87      0.88     17110
           X       0.62      0.04      0.07       134

    accuracy                           0.90    153590
   macro avg       0.82      0.75      0.76    153590
weighted avg       0.89      0.90      0.89    153590

HashingVectorizer(analyzer='char', n_features=3000, ngram_range=(1, 5))
              precision    recall  f1-score   support

         ADJ       0.88      0.87      0.87     15103
         ADP       0.98      0.99      0.99     13717
         ADV       0.88      0.84      0.86      7783
         AUX       0.81      0.97      0.88      1390
       CCONJ       0.88      0.99      0.93      5672
         DET       0.85      0.76      0.80      4265
        INTJ       0.00      0.00      0.00        24
        NOUN       0.87      0.94      0.90     36238
      NO_TAG       1.00      0.77      0.87       265
         NUM       0.83      0.86      0.84      1734
        PART       0.95      0.76      0.84      5125
        PRON       0.83      0.87      0.85      7444
       PROPN       0.74      0.42      0.53      5473
       PUNCT       1.00      1.00      1.00     29186
       SCONJ       0.81      0.90      0.85      2865
         SYM       1.00      0.82      0.90        62
        VERB       0.89      0.89      0.89     17110
           X       0.33      0.01      0.01       134

    accuracy                           0.90    153590
   macro avg       0.81      0.76      0.77    153590
weighted avg       0.90      0.90      0.90    153590

HashingVectorizer(analyzer='char', n_features=5000, ngram_range=(1, 5))
              precision    recall  f1-score   support

         ADJ       0.89      0.89      0.89     15103
         ADP       0.98      0.99      0.99     13717
         ADV       0.90      0.85      0.87      7783
         AUX       0.81      0.97      0.88      1390
       CCONJ       0.89      0.97      0.93      5672
         DET       0.88      0.72      0.79      4265
        INTJ       0.00      0.00      0.00        24
        NOUN       0.88      0.95      0.91     36238
      NO_TAG       1.00      0.77      0.87       265
         NUM       0.85      0.85      0.85      1734
        PART       0.93      0.78      0.85      5125
        PRON       0.83      0.90      0.86      7444
       PROPN       0.79      0.46      0.58      5473
       PUNCT       1.00      1.00      1.00     29186
       SCONJ       0.81      0.90      0.85      2865
         SYM       1.00      0.73      0.84        62
        VERB       0.91      0.91      0.91     17110
           X       0.32      0.07      0.11       134

    accuracy                           0.91    153590
   macro avg       0.82      0.76      0.78    153590
weighted avg       0.91      0.91      0.91    153590

HashingVectorizer(n_features=2000, ngram_range=(1, 5))
              precision    recall  f1-score   support

         ADJ       0.47      0.25      0.32     15103
         ADP       0.89      0.47      0.62     13717
         ADV       0.66      0.67      0.66      7783
         AUX       0.75      0.94      0.84      1390
       CCONJ       0.92      0.18      0.30      5672
         DET       0.67      0.50      0.57      4265
        INTJ       0.00      0.00      0.00        24
        NOUN       0.60      0.58      0.59     36238
      NO_TAG       0.00      0.00      0.00       265
         NUM       0.51      0.45      0.48      1734
        PART       0.90      0.75      0.82      5125
        PRON       0.68      0.83      0.75      7444
       PROPN       0.37      0.09      0.15      5473
       PUNCT       0.48      1.00      0.65     29186
       SCONJ       0.76      0.90      0.82      2865
         SYM       0.00      0.00      0.00        62
        VERB       0.54      0.29      0.38     17110
           X       0.00      0.00      0.00       134

    accuracy                           0.58    153590
   macro avg       0.51      0.44      0.44    153590
weighted avg       0.61      0.58      0.55    153590

HashingVectorizer(n_features=3000, ngram_range=(1, 5))
              precision    recall  f1-score   support

         ADJ       0.53      0.27      0.36     15103
         ADP       0.92      0.47      0.62     13717
         ADV       0.75      0.69      0.72      7783
         AUX       0.79      0.74      0.76      1390
       CCONJ       0.93      0.18      0.30      5672
         DET       0.66      0.62      0.64      4265
        INTJ       0.00      0.00      0.00        24
        NOUN       0.63      0.60      0.61     36238
      NO_TAG       0.00      0.00      0.00       265
         NUM       0.59      0.48      0.53      1734
        PART       0.90      0.76      0.82      5125
        PRON       0.78      0.76      0.77      7444
       PROPN       0.44      0.11      0.18      5473
       PUNCT       0.46      1.00      0.63     29186
       SCONJ       0.73      0.95      0.82      2865
         SYM       0.00      0.00      0.00        62
        VERB       0.59      0.32      0.41     17110
           X       0.00      0.00      0.00       134

    accuracy                           0.59    153590
   macro avg       0.54      0.44      0.45    153590
weighted avg       0.64      0.59      0.57    153590

HashingVectorizer(n_features=5000, ngram_range=(1, 5))
              precision    recall  f1-score   support

         ADJ       0.61      0.30      0.41     15103
         ADP       0.92      0.48      0.63     13717
         ADV       0.80      0.71      0.75      7783
         AUX       0.81      0.86      0.83      1390
       CCONJ       0.85      0.20      0.33      5672
         DET       0.77      0.54      0.63      4265
        INTJ       0.00      0.00      0.00        24
        NOUN       0.67      0.62      0.64     36238
      NO_TAG       0.00      0.00      0.00       265
         NUM       0.63      0.49      0.55      1734
        PART       0.93      0.72      0.81      5125
        PRON       0.74      0.82      0.77      7444
       PROPN       0.51      0.14      0.22      5473
       PUNCT       0.45      1.00      0.62     29186
       SCONJ       0.76      0.88      0.81      2865
         SYM       0.00      0.00      0.00        62
        VERB       0.65      0.35      0.46     17110
           X       0.00      0.00      0.00       134

    accuracy                           0.60    153590
   macro avg       0.56      0.45      0.47    153590
weighted avg       0.67      0.60      0.59    153590

In [21]:
pd.set_option('display.max_columns', None)
pd.set_option('display.expand_frame_repr', False)
pd.set_option('max_colwidth', None)

In [22]:
result_model = pd.DataFrame({'Vectorizer': vectorizers + vectorizers_word + vectorizers_hash + vectorizers_hash_word,
                            'f1_score': f1_scores})
result_model.sort_values('f1_score', ascending=False)

                                                                 Vectorizer  f1_score
0                      CountVectorizer(analyzer='char', ngram_range=(1, 5))  0.937951
1                      TfidfVectorizer(analyzer='char', ngram_range=(1, 5))  0.923645
8   HashingVectorizer(analyzer='char', n_features=5000, ngram_range=(1, 5))  0.909227
7   HashingVectorizer(analyzer='char', n_features=3000, ngram_range=(1, 5))  0.899331
6   HashingVectorizer(analyzer='char', n_features=2000, ngram_range=(1, 5))  0.891962
2   HashingVectorizer(analyzer='char', n_features=1000, ngram_range=(1, 5))  0.864832
4                                       TfidfVectorizer(ngram_range=(1, 5))  0.649657
3                                       CountVectorizer(ngram_range=(1, 5))  0.638731
11                   HashingVectorizer(n_features=5000, ngram_range=(1, 5))  0.585121
10                   HashingVectorizer(n_features=3000, ngram_range=(1, 5))  0.565790
9                    HashingVectorizer(n_features=2000, ngram_range=(1, 5))  0.548821
5                    HashingVectorizer(n_features=1000, ngram_range=(1, 5))  0.341190

In [23]:
result_model_acc = pd.DataFrame({'Vectorizer': vectorizers + vectorizers_word + vectorizers_hash + vectorizers_hash_word,
                            'Accuracy': accuracy_scores})
result_model_acc.sort_values('Accuracy', ascending=False)

                                                                 Vectorizer  Accuracy
0                      CountVectorizer(analyzer='char', ngram_range=(1, 5))  0.939456
1                      TfidfVectorizer(analyzer='char', ngram_range=(1, 5))  0.926818
8   HashingVectorizer(analyzer='char', n_features=5000, ngram_range=(1, 5))  0.912403
7   HashingVectorizer(analyzer='char', n_features=3000, ngram_range=(1, 5))  0.903067
6   HashingVectorizer(analyzer='char', n_features=2000, ngram_range=(1, 5))  0.895540
2   HashingVectorizer(analyzer='char', n_features=1000, ngram_range=(1, 5))  0.868650
4                                       TfidfVectorizer(ngram_range=(1, 5))  0.639306
3                                       CountVectorizer(ngram_range=(1, 5))  0.627821
11                   HashingVectorizer(n_features=5000, ngram_range=(1, 5))  0.603848
10                   HashingVectorizer(n_features=3000, ngram_range=(1, 5))  0.589661
9                    HashingVectorizer(n_features=2000, ngram_range=(1, 5))  0.578137
5                    HashingVectorizer(n_features=1000, ngram_range=(1, 5))  0.361130

В результате эксперимента проверили различные векторайзеры для разного количества символов. Наилучший результат показали символьные N-граммы. Результат N-грамм для слов оказался значительно хуже.

Задание 2.

NLTK

In [24]:
nltk.download('tagsets')
nltk.download('averaged_perceptron_tagger')
nltk.download('maxent_ne_chunker')
nltk.download('words')

[nltk_data] Downloading package tagsets to /root/nltk_data...
[nltk_data]   Unzipping help/tagsets.zip.
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data] Downloading package maxent_ne_chunker to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping chunkers/maxent_ne_chunker.zip.
[nltk_data] Downloading package words to /root/nltk_data...
[nltk_data]   Unzipping corpora/words.zip.

True

In [25]:
nltk.help.upenn_tagset('RB')
nltk.help.upenn_tagset('NN')
nltk.help.upenn_tagset('VB')

RB: adverb
    occasionally unabatingly maddeningly adventurously professedly
    stirringly prominently technologically magisterially predominately
    swiftly fiscally pitilessly ...
NN: noun, common, singular or mass
    common-carrier cabbage knuckle-duster Casino afghan shed thermostat
    investment slide humour falloff slick wind hyena override subhumanity
    machinist ...
VB: verb, base form
    ask assemble assess assign assume atone attention avoid bake balkanize
    bank begin behold believe bend benefit bevel beware bless boil bomb
    boost brace break bring broil brush build ...

In [26]:
!wget http://www.labinform.ru/pub/named_entities/collection5.zip

--2023-12-04 19:56:48--  http://www.labinform.ru/pub/named_entities/collection5.zip
Resolving www.labinform.ru (www.labinform.ru)... 95.181.230.181
Connecting to www.labinform.ru (www.labinform.ru)|95.181.230.181|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1899530 (1.8M) [application/zip]
Saving to: ‘collection5.zip’

collection5.zip     100%[===================>]   1.81M  2.00MB/s    in 0.9s

2023-12-04 19:56:49 (2.00 MB/s) - ‘collection5.zip’ saved [1899530/1899530]

In [27]:
!unzip collection5.zip

Archive:  collection5.zip
   creating: Collection5/
  inflating: Collection5/001.ann
  inflating: Collection5/001.txt
  inflating: Collection5/002.ann
  inflating: Collection5/002.txt
  inflating: Collection5/003.ann
  inflating: Collection5/003.txt
  inflating: Collection5/004.ann
  inflating: Collection5/004.txt
  inflating: Collection5/005.ann
  inflating: Collection5/005.txt
  inflating: Collection5/006.ann
  inflating: Collection5/006.txt
  inflating: Collection5/007.ann
  inflating: Collection5/007.txt
  inflating: Collection5/008.ann
  inflating: Collection5/008.txt
  inflating: Collection5/009.ann
  inflating: Collection5/009.txt
  inflating: Collection5/010.ann
  inflating: Collection5/010.txt
  inflating: Collection5/011.ann
  inflating: Collection5/011.txt
  inflating: Collection5/012.ann
  inflating: Collection5/012.txt
  inflating: Collection5/013.ann
  inflating: Collection5/013.txt
  inflating: Collection5/014.ann
  inflating: Collection5/014.txt
  inflating: Collection5/015 (!).ann
  inflating: Collection5/015 (!).txt
  inflating: Collection5/016.ann
  inflating: Collection5/016.txt
  inflating: Collection5/017.ann
  inflating: Collection5/017.txt
  inflating: Collection5/018.ann
  inflating: Collection5/018.txt
  inflating: Collection5/019.ann
  inflating: Collection5/019.txt
  inflating: Collection5/020.ann
  inflating: Collection5/020.txt
  inflating: Collection5/021.ann
  inflating: Collection5/021.txt
  inflating: Collection5/022.ann
  inflating: Collection5/022.txt
  inflating: Collection5/023.ann
  inflating: Collection5/023.txt
  inflating: Collection5/025.ann
  inflating: Collection5/025.txt
  inflating: Collection5/026.ann
  inflating: Collection5/026.txt
  inflating: Collection5/027.ann
  inflating: Collection5/027.txt
  inflating: Collection5/028.ann
  inflating: Collection5/028.txt
  inflating: Collection5/029.ann
  inflating: Collection5/029.txt
  inflating: Collection5/030.ann
  inflating: Collection5/030.txt
  inflating: Collection5/031.ann
  inflating: Collection5/031.txt
  inflating: Collection5/032.ann
  inflating: Collection5/032.txt
  inflating: Collection5/033.ann
  inflating: Collection5/033.txt
  inflating: Collection5/034.ann
  inflating: Collection5/034.txt
  inflating: Collection5/035.ann
  inflating: Collection5/035.txt
  inflating: Collection5/036.ann
  inflating: Collection5/036.txt
  inflating: Collection5/037.ann
  inflating: Collection5/037.txt
  inflating: Collection5/038.ann
  inflating: Collection5/038.txt
  inflating: Collection5/039.ann
  inflating: Collection5/039.txt
  inflating: Collection5/03_12_12a.ann
  inflating: Collection5/03_12_12a.txt
  inflating: Collection5/03_12_12b.ann
  inflating: Collection5/03_12_12b.txt
  inflating: Collection5/03_12_12c.ann
  inflating: Collection5/03_12_12c.txt
  inflating: Collection5/03_12_12d.ann
  inflating: Collection5/03_12_12d.txt
  inflating: Collection5/03_12_12g.ann
  inflating: Collection5/03_12_12g.txt
  inflating: Collection5/03_12_12h.ann
  inflating: Collection5/03_12_12h.txt
  inflating: Collection5/040.ann
  inflating: Collection5/040.txt
  inflating: Collection5/041.ann
  inflating: Collection5/041.txt
  inflating: Collection5/042.ann
  inflating: Collection5/042.txt
  inflating: Collection5/043.ann
  inflating: Collection5/043.txt
  inflating: Collection5/044.ann
  inflating: Collection5/044.txt
  inflating: Collection5/045.ann
  inflating: Collection5/045.txt
  inflating: Collection5/046.ann
  inflating: Collection5/046.txt
  inflating: Collection5/047.ann
  inflating: Collection5/047.txt
  inflating: Collection5/048.ann
  inflating: Collection5/048.txt
  inflating: Collection5/049.ann
  inflating: Collection5/049.txt
  inflating: Collection5/04_02_13a_abdulatipov.ann
  inflating: Collection5/04_02_13a_abdulatipov.txt
  inflating: Collection5/04_03_13a_sorokin.ann
  inflating: Collection5/04_03_13a_sorokin.txt
  inflating: Collection5/04_12_12b.ann
  inflating: Collection5/04_12_12b.txt
  inflating: Collection5/04_12_12d.ann
  inflating: Collection5/04_12_12d.txt
  inflating: Collection5/04_12_12f.ann
  inflating: Collection5/04_12_12f.txt
  inflating: Collection5/04_12_12g.ann
  inflating: Collection5/04_12_12g.txt
  inflating: Collection5/04_12_12h_corr.ann
  inflating: Collection5/04_12_12h_corr.txt
  inflating: Collection5/050.ann
  inflating: Collection5/050.txt
  inflating: Collection5/051.ann
  inflating: Collection5/051.txt
  inflating: Collection5/052.ann
  inflating: Collection5/052.txt
  inflating: Collection5/053.ann
  inflating: Collection5/053.txt
  inflating: Collection5/054.ann
  inflating: Collection5/054.txt
  inflating: Collection5/055.ann
  inflating: Collection5/055.txt
  inflating: Collection5/056.ann
  inflating: Collection5/056.txt
  inflating: Collection5/057.ann
  inflating: Collection5/057.txt
  inflating: Collection5/058.ann
  inflating: Collection5/058.txt
  inflating: Collection5/059.ann
  inflating: Collection5/059.txt
  inflating: Collection5/060.ann
  inflating: Collection5/060.txt
  inflating: Collection5/061.ann
  inflating: Collection5/061.txt
  inflating: Collection5/062.ann
  inflating: Collection5/062.txt
  inflating: Collection5/063.ann
  inflating: Collection5/063.txt
  inflating: Collection5/064.ann
  inflating: Collection5/064.txt
  inflating: Collection5/065.ann
  inflating: Collection5/065.txt
  inflating: Collection5/066.ann
  inflating: Collection5/066.txt
  inflating: Collection5/067.ann
  inflating: Collection5/067.txt
  inflating: Collection5/068.ann
  inflating: Collection5/068.txt
  inflating: Collection5/069.ann
  inflating: Collection5/069.txt
  inflating: Collection5/070.ann
  inflating: Collection5/070.txt
  inflating: Collection5/071.ann
  inflating: Collection5/071.txt
  inflating: Collection5/072.ann
  inflating: Collection5/072.txt
  inflating: Collection5/073.ann
  inflating: Collection5/073.txt
  inflating: Collection5/074.ann
  inflating: Collection5/074.txt
  inflating: Collection5/075.ann
  inflating: Collection5/075.txt
  inflating: Collection5/076.ann
  inflating: Collection5/076.txt
  inflating: Collection5/077.ann
  inflating: Collection5/077.txt
  inflating: Collection5/078.ann
  inflating: Collection5/078.txt
  inflating: Collection5/079.ann
  inflating: Collection5/079.txt
  inflating: Collection5/080.ann
  inflating: Collection5/080.txt
  inflating: Collection5/081.ann
  inflating: Collection5/081.txt
  inflating: Collection5/082.ann
  inflating: Collection5/082.txt
  inflating: Collection5/083.ann
  inflating: Collection5/083.txt
  inflating: Collection5/084.ann
  inflating: Collection5/084.txt
  inflating: Collection5/085.ann
  inflating: Collection5/085.txt
  inflating: Collection5/086.ann
  inflating: Collection5/086.txt
  inflating: Collection5/087.ann
  inflating: Collection5/087.txt
  inflating: Collection5/088.ann
  inflating: Collection5/088.txt
  inflating: Collection5/089.ann
  inflating: Collection5/089.txt
  inflating: Collection5/090.ann
  inflating: Collection5/090.txt
  inflating: Collection5/091.ann
  inflating: Collection5/091.txt
  inflating: Collection5/092.ann
  inflating: Collection5/092.txt
  inflating: Collection5/093.ann
  inflating: Collection5/093.txt
  inflating: Collection5/094.ann
  inflating: Collection5/094.txt
  inflating: Collection5/095.ann
  inflating: Collection5/095.txt
  inflating: Collection5/096.ann
  inflating: Collection5/096.txt
  inflating: Collection5/097.ann
  inflating: Collection5/097.txt
  inflating: Collection5/098.ann
  inflating: Collection5/098.txt
  inflating: Collection5/099.ann
  inflating: Collection5/099.txt
  inflating: Collection5/09_01_13.ann
  inflating: Collection5/09_01_13.txt
  inflating: Collection5/09_01_13a.ann
  inflating: Collection5/09_01_13a.txt
  inflating: Collection5/09_01_13c.ann
  inflating: Collection5/09_01_13c.txt
  inflating: Collection5/09_01_13d.ann
  inflating: Collection5/09_01_13d.txt
  inflating: Collection5/09_01_13e.ann
  inflating: Collection5/09_01_13e.txt
  inflating: Collection5/09_01_13h.ann
  inflating: Collection5/09_01_13h.txt
  inflating: Collection5/09_01_13i.ann
  inflating: Collection5/09_01_13i.txt
  inflating: Collection5/100.ann
  inflating: Collection5/100.txt
  inflating: Collection5/1000.ann
  inflating: Collection5/1000.txt
  inflating: Collection5/1001.ann
  inflating: Collection5/1001.txt
  inflating: Collection5/1002.ann
  inflating: Collection5/1002.txt
  inflating: Collection5/1003.ann
  inflating: Collection5/1003.txt
  inflating: Collection5/1004.ann
  inflating: Collection5/1004.txt
  inflating: Collection5/1005.ann
  inflating: Collection5/1005.txt
  inflating: Collection5/1006.ann
  inflating: Collection5/1006.txt
  inflating: Collection5/1007.ann
  inflating: Collection5/1007.txt
  inflating: Collection5/1008.ann
  inflating: Collection5/1008.txt
  inflating: Collection5/1009.ann
  inflating: Collection5/1009.txt
  inflating: Collection5/101.ann
  inflating: Collection5/101.txt
  inflating: Collection5/1010.ann
  inflating: Collection5/1010.txt
  inflating: Collection5/1011.ann
  inflating: Collection5/1011.txt
  inflating: Collection5/1012.ann
  inflating: Collection5/1012.txt
  inflating: Collection5/1013.ann
  inflating: Collection5/1013.txt
  inflating: Collection5/1014.ann
  inflating: Collection5/1014.txt
  inflating: Collection5/1015.ann
  inflating: Collection5/1015.txt
  inflating: Collection5/1016.ann
  inflating: Collection5/1016.txt
  inflating: Collection5/1017.ann
  inflating: Collection5/1017.txt
  inflating: Collection5/1018.ann
  inflating: Collection5/1018.txt
  inflating: Collection5/1019.ann
  inflating: Collection5/1019.txt
  inflating: Collection5/102.ann
  inflating: Collection5/102.txt
  inflating: Collection5/1020.ann
  inflating: Collection5/1020.txt
  inflating: Collection5/1021.ann
  inflating: Collection5/1021.txt
  inflating: Collection5/1022.ann
  inflating: Collection5/1022.txt
  inflating: Collection5/1023.ann
  inflating: Collection5/1023.txt
  inflating: Collection5/1024.ann
  inflating: Collection5/1024.txt
  inflating: Collection5/1025.ann
  inflating: Collection5/1025.txt
  inflating: Collection5/1026.ann
  inflating: Collection5/1026.txt
  inflating: Collection5/1027.ann
  inflating: Collection5/1027.txt
  inflating: Collection5/1028.ann
  inflating: Collection5/1028.txt
  inflating: Collection5/1029.ann
  inflating: Collection5/1029.txt
  inflating: Collection5/103.ann
  inflating: Collection5/103.txt
  inflating: Collection5/1030.ann
  inflating: Collection5/1030.txt
  inflating: Collection5/1031.ann
  inflating: Collection5/1031.txt
  inflating: Collection5/1032.ann
  inflating: Collection5/1032.txt
  inflating: Collection5/1033.ann
  inflating: Collection5/1033.txt
  inflating: Collection5/1034.ann
  inflating: Collection5/1034.txt
  inflating: Collection5/1035.ann
  inflating: Collection5/1035.txt
  inflating: Collection5/1036.ann
  inflating: Collection5/1036.txt
  inflating: Collection5/1037.ann
  inflating: Collection5/1037.txt
  inflating: Collection5/1038.ann
  inflating: Collection5/1038.txt
  inflating: Collection5/1039.ann
  inflating: Collection5/1039.txt
  inflating: Collection5/104.ann
  inflating: Collection5/104.txt
  inflating: Collection5/1040.ann
  inflating: Collection5/1040.txt
  inflating: Collection5/1041.ann
  inflating: Collection5/1041.txt
  inflating: Collection5/1042.ann
  inflating: Collection5/1042.txt
  inflating: Collection5/1043.ann
  inflating: Collection5/1043.txt
  inflating: Collection5/1044.ann
  inflating: Collection5/1044.txt
  inflating: Collection5/1045.ann
  inflating: Collection5/1045.txt
  inflating: Collection5/1046.ann
  inflating: Collection5/1046.txt
  inflating: Collection5/1047.ann
  inflating: Collection5/1047.txt
  inflating: Collection5/1048.ann
  inflating: Collection5/1048.txt
  inflating: Collection5/1049.ann
  inflating: Collection5/1049.txt
  inflating: Collection5/105.ann
  inflating: Collection5/105.txt
  inflating: Collection5/1050.ann
  inflating: Collection5/1050.txt
  inflating: Collection5/106.ann
  inflating: Collection5/106.txt
  inflating: Collection5/107.ann
  inflating: Collection5/107.txt
  inflating: Collection5/108.ann
  inflating: Collection5/108.txt
  inflating: Collection5/109.ann
  inflating: Collection5/109.txt
  inflating: Collection5/10_01_13a.ann
  inflating: Collection5/10_01_13a.txt
  inflating: Collection5/10_01_13d.ann
  inflating: Collection5/10_01_13d.txt
  inflating: Collection5/10_01_13i.ann
  inflating: Collection5/10_01_13i.txt
  inflating: Collection5/110.ann
  inflating: Collection5/110.txt
  inflating: Collection5/1100.ann
  inflating: Collection5/1100.txt
  inflating: Collection5/1101.ann
  inflating: Collection5/1101.txt
  inflating: Collection5/1102.ann
  inflating: Collection5/1102.txt
  inflating: Collection5/1103.ann
  inflating: Collection5/1103.txt
  inflating: Collection5/1104.ann
  inflating: Collection5/1104.txt
  inflating: Collection5/1105.ann
  inflating: Collection5/1105.txt
  inflating: Collection5/1106.ann
  inflating: Collection5/1106.txt
  inflating: Collection5/1107.ann
  inflating: Collection5/1107.txt
  inflating: Collection5/1108.ann
  inflating: Collection5/1108.txt
  inflating: Collection5/1109.ann
  inflating: Collection5/1109.txt
  inflating: Collection5/111.ann
  inflating: Collection5/111.txt
  inflating: Collection5/1110.ann
  inflating: Collection5/1110.txt
  inflating: Collection5/1111.ann
  inflating: Collection5/1111.txt
  inflating: Collection5/1112.ann
  inflating: Collection5/1112.txt
  inflating: Collection5/1113.ann
  inflating: Collection5/1113.txt
  inflating: Collection5/1114.ann
  inflating: Collection5/1114.txt
  inflating: Collection5/1115.ann
  inflating: Collection5/1115.txt
  inflating: Collection5/1116.ann
  inflating: Collection5/1116.txt
  inflating: Collection5/1117.ann
  inflating: Collection5/1117.txt
  inflating: Collection5/1118.ann
  inflating: Collection5/1118.txt
  inflating: Collection5/1119.ann
  inflating: Collection5/1119.txt
  inflating: Collection5/112.ann
  inflating: Collection5/112.txt
  inflating: Collection5/1120.ann
  inflating: Collection5/1120.txt
  inflating: Collection5/1121.ann
  inflating: Collection5/1121.txt
  inflating: Collection5/1122.ann
  inflating: Collection5/1122.txt
  inflating: Collection5/1123.ann
  inflating: Collection5/1123.txt
  inflating: Collection5/1124.ann
  inflating: Collection5/1124.txt
  inflating: Collection5/1125.ann
  inflating: Collection5/1125.txt
  inflating: Collection5/1126.ann
  inflating: Collection5/1126.txt
  inflating: Collection5/1127.ann
  inflating: Collection5/1127.txt
  inflating: Collection5/1128.ann
  inflating: Collection5/1128.txt
  inflating: Collection5/113.ann
  inflating: Collection5/113.txt
  inflating: Collection5/1130.ann
  inflating: Collection5/1130.txt
  inflating: Collection5/1131.ann
  inflating: Collection5/1131.txt
  inflating: Collection5/1132.ann
  inflating: Collection5/1132.txt
  inflating: Collection5/1133.ann
  inflating: Collection5/1133.txt
  inflating: Collection5/1134.ann
  inflating: Collection5/1134.txt
  inflating: Collection5/1135.ann
  inflating: Collection5/1135.txt
  inflating: Collection5/1136.ann
  inflating: Collection5/1136.txt
  inflating: Collection5/1137.ann
  inflating: Collection5/1137.txt
  inflating: Collection5/1138.ann
  inflating: Collection5/1138.txt
  inflating: Collection5/1139.ann
  inflating: Collection5/1139.txt
  inflating: Collection5/114.ann
  inflating: Collection5/114.txt
  inflating: Collection5/1140.ann
  inflating: Collection5/1140.txt
  inflating: Collection5/1141.ann
  inflating: Collection5/1141.txt
  inflating: Collection5/1142.ann
  inflating: Collection5/1142.txt
  inflating: Collection5/1143.ann
  inflating: Collection5/1143.txt
  inflating: Collection5/1144.ann
  inflating: Collection5/1144.txt
  inflating: Collection5/1145.ann
  inflating: Collection5/1145.txt
  inflating: Collection5/1146.ann
  inflating: Collection5/1146.txt
  inflating: Collection5/1147.ann
  inflating: Collection5/1147.txt
  inflating: Collection5/1148.ann
  inflating: Collection5/1148.txt
  inflating: Collection5/1149.ann
  inflating: Collection5/1149.txt
  inflating: Collection5/115.ann
  inflating: Collection5/115.txt
  inflating: Collection5/1150.ann
  inflating: Collection5/1150.txt
  inflating: Collection5/1151.ann
  inflating: Collection5/1151.txt
  inflating: Collection5/1152.ann
  inflating: Collection5/1152.txt
  inflating: Collection5/1153.ann
  inflating: Collection5/1153.txt
  inflating: Collection5/1154.ann
  inflating: Collection5/1154.txt
  inflating: Collection5/1155.ann
  inflating: Collection5/1155.txt
  inflating: Collection5/1156.ann
  inflating: Collection5/1156.txt
  inflating: Collection5/1157.ann
  inflating: Collection5/1157.txt
  inflating: Collection5/1158.ann
  inflating: Collection5/1158.txt
  inflating: Collection5/1159.ann
  inflating: Collection5/1159.txt
  inflating: Collection5/116.ann
  inflating: Collection5/116.txt
  inflating: Collection5/1160.ann
  inflating: Collection5/1160.txt
  inflating: Collection5/1161.ann
  inflating: Collection5/1161.txt
  inflating: Collection5/1162.ann
  inflating: Collection5/1162.txt
  inflating: Collection5/1163.ann
  inflating: Collection5/1163.txt
  inflating: Collection5/1164.ann
  inflating: Collection5/1164.txt
  inflating: Collection5/1165.ann
  inflating: Collection5/1165.txt
  inflating: Collection5/1166.ann
  inflating: Collection5/1166.txt
  inflating: Collection5/1167.ann
  inflating: Collection5/1167.txt
  inflating: Collection5/1168.ann
  inflating: Collection5/1168.txt
  inflating: Collection5/1169.ann
  inflating: Collection5/1169.txt
  inflating: Collection5/117.ann
  inflating: Collection5/117.txt
  inflating: Collection5/1170.ann
  inflating: Collection5/1170.txt
  inflating: Collection5/1171.ann
  inflating: Collection5/1171.txt
  inflating: Collection5/1172.ann
  inflating: Collection5/1172.txt
  inflating: Collection5/1173.ann
  inflating: Collection5/1173.txt
  inflating: Collection5/1174.ann
  inflating: Collection5/1174.txt
  inflating: Collection5/1175.ann
  inflating: Collection5/1175.txt
  inflating: Collection5/1176.ann
  inflating: Collection5/1176.txt
  inflating: Collection5/1177.ann
  inflating: Collection5/1177.txt
  inflating: Collection5/1178.ann
  inflating: Collection5/1178.txt
  inflating: Collection5/1179.ann
  inflating: Collection5/1179.txt
  inflating: Collection5/118.ann
  inflating: Collection5/118.txt
  inflating: Collection5/1180.ann
  inflating: Collection5/1180.txt
  inflating: Collection5/1181.ann
  inflating: Collection5/1181.txt
  inflating: Collection5/1182.ann
  inflating: Collection5/1182.txt
  inflating: Collection5/1183.ann
  inflating: Collection5/1183.txt
  inflating: Collection5/1184.ann
  inflating: Collection5/1184.txt
  inflating: Collection5/1185.ann
  inflating: Collection5/1185.txt
  inflating: Collection5/1186.ann
  inflating: Collection5/1186.txt
  inflating: Collection5/1187.ann
  inflating: Collection5/1187.txt
  inflating: Collection5/1188.ann
  inflating: Collection5/1188.txt
  inflating: Collection5/1189.ann
  inflating: Collection5/1189.txt
  inflating: Collection5/119.ann
  inflating: Collection5/119.txt
  inflating: Collection5/1190.ann
  inflating: Collection5/1190.txt
  inflating: Collection5/1191.ann
  inflating: Collection5/1191.txt
  inflating: Collection5/1192.ann
  inflating: Collection5/1192.txt
  inflating: Collection5/1193.ann
  inflating: Collection5/1193.txt
  inflating: Collection5/1194.ann
  inflating: Collection5/1194.txt
  inflating: Collection5/1195.ann
  inflating: Collection5/1195.txt
  inflating: Collection5/1196.ann
  inflating: Collection5/1196.txt
  inflating: Collection5/1197.ann
  inflating: Collection5/1197.txt
  inflating: Collection5/1198.ann
  inflating: Collection5/1198.txt
  inflating: Collection5/1199.ann
  inflating: Collection5/1199.txt
  inflating: Collection5/11_01_13b.ann
  inflating: Collection5/11_01_13b.txt

In [28]:
records = load_ne5('Collection5/')

In [29]:
document = next(records)
text = document.text
# text
text = re.sub('\r\n\r\n',' ',text)
text = re.sub('\r\n',' ',text)
text

'Губернатор Югры назначила нового заместителя по строительству и ЖКХ  Губернатор Ханты-Мансийского автономного округа - Югры Наталья Комарова назначила на должность своего заместителя Дмитрия Шаповала; в его ведении будут находиться окружные департаменты дорожного хозяйства и транспорта, строительства, ЖКХ и энергетики. Губернатор Ханты-Мансийского автономного округа – Югры Наталья Комарова. Архив  Губернатор Ханты-Мансийского автономного округа — Югры Наталья Комарова назначила на должность своего заместителя Дмитрия Шаповала; в его ведении будут находиться окружные департаменты дорожного хозяйства и транспорта, строительства, ЖКХ и энергетики, сообщает пресс-служба губернатора. "Новым заместителем главы региона с 21 июня 2013 года назначен Дмитрий Викторович Шаповал, который будет отвечать за окружные департаменты дорожного хозяйства и транспорта, строительства, ЖКХ и энергетики, гражданской защиты населения, а также служба государственного надзора за техническим состоянием самоходных машин и других видов техники. Ранее этот пост в правительстве Югры занимал Валентин Грипас, который 20 июня уволен по собственному желанию", — говорится в сообщении. Дмитрий Шаповал родился в Магнитогорске в 1979 году. Окончил Магнитогорский государственный технический университет им. Носова, защитил диссертацию по специальности "строительные конструкции зданий и сооружений". В 2011 году назначен заместителем директора департамента строительства, энергетики и жилищно-коммунального комплекса Югры, в котором курировал вопросы строительства, после чего возглавил департамент архитектуры, строительства и градостроительной политики министерства регионального развития Российской Федерации и проработал в этой должности до 2012 года. С 2012 по 2013 год занимал пост министра строительства и архитектуры Пермского края. В 2013 году был назначен директором департамента взаимодействия с органами государственной власти Национального объединения строителей.'

In [30]:
document.text = text

In [32]:
nltk.download('punkt')
nltk.pos_tag(nltk.word_tokenize(text)) # Как предварительно очистить все статьи в словаре.

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

[('Губернатор', 'JJ'),
 ('Югры', 'NNP'),
 ('назначила', 'NNP'),
 ('нового', 'NNP'),
 ('заместителя', 'NNP'),
 ('по', 'NNP'),
 ('строительству', 'NNP'),
 ('и', 'NNP'),
 ('ЖКХ', 'NNP'),
 ('Губернатор', 'NNP'),
 ('Ханты-Мансийского', 'JJ'),
 ('автономного', 'NNP'),
 ('округа', 'NNP'),
 ('-', ':'),
 ('Югры', 'NN'),
 ('Наталья', 'JJ'),
 ('Комарова', 'NNP'),
 ('назначила', 'NNP'),
 ('на', 'NNP'),
 ('должность', 'NNP'),
 ('своего', 'NNP'),
 ('заместителя', 'NNP'),
 ('Дмитрия', 'NNP'),
 ('Шаповала', 'NNP'),
 (';', ':'),
 ('в', 'NNP'),
 ('его', 'NNP'),
 ('ведении', 'NNP'),
 ('будут', 'NNP'),
 ('находиться', 'NNP'),
 ('окружные', 'NNP'),
 ('департаменты', 'NNP'),
 ('дорожного', 'NNP'),
 ('хозяйства', 'NNP'),
 ('и', 'NNP'),
 ('транспорта', 'NNP'),
 (',', ','),
 ('строительства', 'NNP'),
 (',', ','),
 ('ЖКХ', 'NNP'),
 ('и', 'NNP'),
 ('энергетики', 'NNP'),
 ('.', '.'),
 ('Губернатор', 'VB'),
 ('Ханты-Мансийского', 'JJ'),
 ('автономного', 'NNP'),
 ('округа', 'NNP'),
 ('–', 'NNP'),
 ('Югры', 'NNP'),
 ('Наталья', 'NNP'),
 ('Комарова', 'NNP'),
 ('.', '.'),
 ('Архив', 'VB'),
 ('Губернатор', 'JJ'),
 ('Ханты-Мансийского', 'JJ'),
 ('автономного', 'NN'),
 ('округа', 'NNP'),
 ('—', 'NNP'),
 ('Югры', 'NNP'),
 ('Наталья', 'NNP'),
 ('Комарова', 'NNP'),
 ('назначила', 'NNP'),
 ('на', 'NNP'),
 ('должность', 'NNP'),
 ('своего', 'NNP'),
 ('заместителя', 'NNP'),
 ('Дмитрия', 'NNP'),
 ('Шаповала', 'NNP'),
 (';', ':'),
 ('в', 'NNP'),
 ('его', 'NNP'),
 ('ведении', 'NNP'),
 ('будут', 'NNP'),
 ('находиться', 'NNP'),
 ('окружные', 'NNP'),
 ('департаменты', 'NNP'),
 ('дорожного', 'NNP'),
 ('хозяйства', 'NNP'),
 ('и', 'NNP'),
 ('транспорта', 'NNP'),
 (',', ','),
 ('строительства', 'NNP'),
 (',', ','),
 ('ЖКХ', 'NNP'),
 ('и', 'NNP'),
 ('энергетики', 'NNP'),
 (',', ','),
 ('сообщает', 'NNP'),
 ('пресс-служба', 'NNP'),
 ('губернатора', 'NNP'),
 ('.', '.'),
 ('``', '``'),
 ('Новым', 'JJ'),
 ('заместителем', 'NN'),
 ('главы', 'NNP'),
 ('региона', 'NNP'),
 ('с', 'VBD'),
 ('21', 'CD'),
 ('июня', 'NN'),
 ('2013', 'CD'),
 ('года', 'NNP'),
 ('назначен', 'NNP'),
 ('Дмитрий', 'NNP'),
 ('Викторович', 'NNP'),
 ('Шаповал', 'NNP'),
 (',', ','),
 ('который', 'NNP'),
 ('будет', 'NNP'),
 ('отвечать', 'NNP'),
 ('за', 'NNP'),
 ('окружные', 'NNP'),
 ('департаменты', 'NNP'),
 ('дорожного', 'NNP'),
 ('хозяйства', 'NNP'),
 ('и', 'NNP'),
 ('транспорта', 'NNP'),
 (',', ','),
 ('строительства', 'NNP'),
 (',', ','),
 ('ЖКХ', 'NNP'),
 ('и', 'NNP'),
 ('энергетики', 'NNP'),
 (',', ','),
 ('гражданской', 'NNP'),
 ('защиты', 'NNP'),
 ('населения', 'NNP'),
 (',', ','),
 ('а', 'NNP'),
 ('также', 'NNP'),
 ('служба', 'NNP'),
 ('государственного', 'NNP'),
 ('надзора', 'NNP'),
 ('за', 'NNP'),
 ('техническим', 'NNP'),
 ('состоянием', 'NNP'),
 ('самоходных', 'NNP'),
 ('машин', 'NNP'),
 ('и', 'NNP'),
 ('других', 'NNP'),
 ('видов', 'NNP'),
 ('техники', 'NNP'),
 ('.', '.'),
 ('Ранее', 'VB'),
 ('этот', 'JJ'),
 ('пост', 'NNP'),
 ('в', 'NNP'),
 ('правительстве', 'NNP'),
 ('Югры', 'NNP'),
 ('занимал', 'NNP'),
 ('Валентин', 'NNP'),
 ('Грипас', 'NNP'),
 (',', ','),
 ('который', 'VBD'),
 ('20', 'CD'),
 ('июня', 'NNP'),
 ('уволен', 'NNP'),
 ('по', 'NNP'),
 ('собственному', 'NNP'),
 ('желанию', 'NNP'),
 ("''", "''"),
 (',', ','),
 ('—', 'NNP'),
 ('говорится', 'NNP'),
 ('в', 'NNP'),
 ('сообщении', 'NNP'),
 ('.', '.'),
 ('Дмитрий', 'VB'),
 ('Шаповал', 'JJ'),
 ('родился', 'NNP'),
 ('в', 'NNP'),
 ('Магнитогорске', 'NNP'),
 ('в', 'NNP'),
 ('1979', 'CD'),
 ('году', 'NNP'),
 ('.', '.'),
 ('Окончил', 'VB'),
 ('Магнитогорский', 'JJ'),
 ('государственный', 'NNP'),
 ('технический', 'NNP'),
 ('университет', 'NNP'),
 ('им', 'NNP'),
 ('.', '.'),
 ('Носова', 'NN'),
 (',', ','),
 ('защитил', 'NNP'),
 ('диссертацию', 'NNP'),
 ('по', 'NNP'),
 ('специальности', 'NNP'),
 ('``', '``'),
 ('строительные', 'NNP'),
 ('конструкции', 'NNP'),
 ('зданий', 'NNP'),
 ('и', 'NNP'),
 ('сооружений', 'NNP'),
 ("''", "''"),
 ('.', '.'),
 ('В', 'VB'),
 ('2011', 'CD'),
 ('году', 'NNP'),
 ('назначен', 'NNP'),
 ('заместителем', 'NNP'),
 ('директора', 'NNP'),
 ('департамента', 'NNP'),
 ('строительства', 'NNP'),
 (',', ','),
 ('энергетики', 'NNP'),
 ('и', 'NNP'),
 ('жилищно-коммунального', 'JJ'),
 ('комплекса', 'NNP'),
 ('Югры', 'NNP'),
 (',', ','),
 ('в', 'NNP'),
 ('котором', 'NNP'),
 ('курировал', 'NNP'),
 ('вопросы', 'NNP'),
 ('строительства', 'NNP'),
 (',', ','),
 ('после', 'NNP'),
 ('чего', 'NNP'),
 ('возглавил', 'NNP'),
 ('департамент', 'NNP'),
 ('архитектуры', 'NNP'),
 (',', ','),
 ('строительства', 'NNP'),
 ('и', 'NNP'),
 ('градостроительной', 'NNP'),
 ('политики', 'NNP'),
 ('министерства', 'NNP'),
 ('регионального', 'NNP'),
 ('развития', 'NNP'),
 ('Российской', 'NNP'),
 ('Федерации', 'NNP'),
 ('и', 'NNP'),
 ('проработал', 'NNP'),
 ('в', 'NNP'),
 ('этой', 'NNP'),
 ('должности', 'NNP'),
 ('до', 'NNP'),
 ('2012', 'CD'),
 ('года', 'NNP'),
 ('.', '.'),
 ('С', 'NN'),
 ('2012', 'CD'),
 ('по', 'NN'),
 ('2013', 'CD'),
 ('год', 'NNP'),
 ('занимал', 'NNP'),
 ('пост', 'NNP'),
 ('министра', 'NNP'),
 ('строительства', 'NNP'),
 ('и', 'NNP'),
 ('архитектуры', 'NNP'),
 ('Пермского', 'NNP'),
 ('края', 'NNP'),
 ('.', '.'),
 ('В', 'NN'),
 ('2013', 'CD'),
 ('году', 'NNP'),
 ('был', 'NNP'),
 ('назначен', 'NNP'),
 ('директором', 'NNP'),
 ('департамента', 'NNP'),
 ('взаимодействия', 'NNP'),
 ('с', 'NNP'),
 ('органами', 'NNP'),
 ('государственной', 'NNP'),
 ('власти', 'NNP'),
 ('Национального', 'NNP'),
 ('объединения', 'NNP'),
 ('строителей', 'NNP'),
 ('.', '.')]

In [33]:
{(' '.join(c[0] for c in chunk), chunk.label() ) for chunk in nltk.ne_chunk(nltk.pos_tag(nltk.word_tokenize(text))) if hasattr(chunk, 'label') }

{('Губернатор', 'ORGANIZATION'),
 ('Губернатор', 'PERSON'),
 ('Дмитрий Викторович Шаповал', 'PERSON'),
 ('Дмитрия Шаповала', 'PERSON'),
 ('ЖКХ', 'ORGANIZATION'),
 ('Магнитогорский', 'PERSON'),
 ('Наталья Комарова', 'PERSON'),
 ('Носова', 'PERSON'),
 ('Шаповал', 'PERSON'),
 ('Югры', 'ORGANIZATION'),
 ('Югры Наталья Комарова', 'PERSON')}

В целом - работает. Но ошибки встречаются.

In [34]:
document.spans

[Ne5Span(
     index='T1',
     type='LOC',
     start=11,
     stop=15,
     text='Югры'
 ),
 Ne5Span(
     index='T2',
     type='LOC',
     start=84,
     stop=127,
     text='Ханты-Мансийского автономного округа - Югры'
 ),
 Ne5Span(
     index='T3',
     type='PER',
     start=128,
     stop=144,
     text='Наталья Комарова'
 ),
 Ne5Span(
     index='T4',
     type='PER',
     start=187,
     stop=203,
     text='Дмитрия Шаповала'
 ),
 Ne5Span(
     index='T5',
     type='LOC',
     start=337,
     stop=380,
     text='Ханты-Мансийского автономного округа – Югры'
 ),
 Ne5Span(
     index='T6',
     type='PER',
     start=381,
     stop=397,
     text='Наталья Комарова'
 ),
 Ne5Span(
     index='T7',
     type='LOC',
     start=420,
     stop=463,
     text='Ханты-Мансийского автономного округа — Югры'
 ),
 Ne5Span(
     index='T8',
     type='PER',
     start=464,
     stop=480,
     text='Наталья Комарова'
 ),
 Ne5Span(
     index='T9',
     type='PER',
     start=523,
     stop=539,
     text='Дмитрия Шаповала'
 ),
 Ne5Span(
     index='T10',
     type='PER',
     start=762,
     stop=788,
     text='Дмитрий Викторович Шаповал'
 ),
 Ne5Span(
     index='T11',
     type='LOC',
     start=1074,
     stop=1078,
     text='Югры'
 ),
 Ne5Span(
     index='T12',
     type='PER',
     start=1087,
     stop=1102,
     text='Валентин Грипас'
 ),
 Ne5Span(
     index='T13',
     type='PER',
     start=1181,
     stop=1196,
     text='Дмитрий Шаповал'
 ),
 Ne5Span(
     index='T14',
     type='LOC',
     start=1207,
     stop=1220,
     text='Магнитогорске'
 ),
 Ne5Span(
     index='T15',
     type='ORG',
     start=1242,
     stop=1307,
     text='Магнитогорский государственный технический университет им. Носова'
 ),
 Ne5Span(
     index='T16',
     type='LOC',
     start=1514,
     stop=1518,
     text='Югры'
 ),
 Ne5Span(
     index='T17',
     type='GEOPOLIT',
     start=1688,
     stop=1708,
     text='Российской Федерации'
 ),
 Ne5Span(
     index='T18',
     type='LOC',
     start=1825,
     stop=1839,
     text='Пермского края'
 )]

SpaCy

In [35]:
!python -m spacy download ru_core_news_sm

2023-12-04 19:58:37.822573: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-12-04 19:58:37.822674: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-12-04 19:58:37.822732: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-12-04 19:58:39.588665: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Collecting ru-core-news-sm==3.7.0
  Downloading https://github.com/explosion/spacy-models/releases/download/ru_core_news_sm-3.7.0/ru_core_news_sm-3.7.0-py3-none-any.whl (15.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.3/15.3 MB 47.4 MB/s eta 0:00:00
Requirement already satisfied: spacy<3.8.0,>=3.7.0 in /usr/local/lib/python3.10/dist-packages (from ru-core-news-sm==3.7.0) (3.7.2)
Requirement already satisfied: pymorphy3>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from ru-core-news-sm==3.7.0) (1.2.1)
Requirement already satisfied: dawg-python>=0.7.1 in /usr/local/lib/python3.10/dist-packages (from pymorphy3>=1.0.0->ru-core-news-sm==3.7.0) (0.7.2)
Requirement already satisfied: docopt-ng>=0.6 in /usr/local/lib/python3.10/dist-packages (from pymorphy3>=1.0.0->ru-core-news-sm==3.7.0) (0.9.0)
Requirement already satisfied: pymorphy3-dicts-ru in /usr/local/lib/python3.10/dist-packages (from pymorphy3>=1.0.0->ru-core-news-sm==3.7.0) (2.4.417150.4580142)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (1.0.10)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (2.0.8)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (3.0.9)
Requirement already satisfied: thinc<8.3.0,>=8.1.8 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (8.1.12)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (1.1.2)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (2.4.8)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (2.0.10)
Requirement already satisfied: weasel<0.4.0,>=0.1.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (0.3.4)
Requirement already satisfied: typer<0.10.0,>=0.3.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (0.9.0)
Requirement already satisfied: smart-open<7.0.0,>=5.2.1 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (6.4.0)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (4.64.1)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (2.31.0)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (1.10.13)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (3.1.2)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (67.7.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (23.2)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (3.3.0)
Requirement already satisfied: numpy>=1.19.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (1.23.5)
Requirement already satisfied: typing-extensions>=4.2.0 in /usr/local/lib/python3.10/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (4.5.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (2023.11.17)
Requirement already satisfied: blis<0.8.0,>=0.7.8 in /usr/local/lib/python3.10/dist-packages (from thinc<8.3.0,>=8.1.8->spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (0.7.11)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /usr/local/lib/python3.10/dist-packages (from thinc<8.3.0,>=8.1.8->spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (0.1.4)
Requirement already satisfied: click<9.0.0,>=7.1.1 in /usr/local/lib/python3.10/dist-packages (from typer<0.10.0,>=0.3.0->spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (8.1.7)
Requirement already satisfied: cloudpathlib<0.17.0,>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from weasel<0.4.0,>=0.1.0->spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (0.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (2.1.3)
✔ Download and installation successful
You can now load the package via spacy.load('ru_core_news_sm')

In [36]:
nlp = spacy.load('ru_core_news_sm')

In [37]:
ny_bb = text
article = nlp(ny_bb)

In [38]:
displacy.render(article, jupyter=True, style='ent')

На этом тексте библиотека SpaCy без ошибок.

Посмотрим на список токенов, частей речи и сущностей.

In [39]:
for token in article:
    print(token.text, token.pos_, token.dep_)

Губернатор NOUN nsubj
Югры PROPN nmod
назначила VERB ROOT
нового ADJ amod
заместителя NOUN obj
по ADP case
строительству NOUN nmod
и CCONJ cc
ЖКХ PROPN conj
  SPACE dep
Губернатор NOUN appos
Ханты ADJ amod
- ADJ amod
Мансийского ADJ amod
автономного ADJ amod
округа NOUN nmod
- NOUN nmod
Югры PROPN nmod
Наталья PROPN appos
Комарова PROPN flat:name
назначила VERB xcomp
на ADP case
должность NOUN obl
своего DET det
заместителя NOUN nmod
Дмитрия PROPN appos
Шаповала PROPN flat:name
; PUNCT punct
в ADP case
его DET det
ведении NOUN obl
будут AUX aux
находиться VERB conj
окружные ADJ amod
департаменты NOUN nsubj
дорожного ADJ amod
хозяйства NOUN nmod
и CCONJ cc
транспорта NOUN conj
, PUNCT punct
строительства NOUN conj
, PUNCT punct
ЖКХ PROPN conj
и CCONJ cc
энергетики NOUN conj
. PUNCT punct
Губернатор NOUN ROOT
Ханты ADJ amod
- ADJ amod
Мансийского ADJ amod
автономного ADJ amod
округа NOUN nmod
– PUNCT punct
Югры PROPN parataxis
Наталья PROPN appos
Комарова PROPN flat:name
. PUNCT punct
Архив NOUN nsubj
  SPACE dep
Губернатор NOUN appos
Ханты ADJ amod
- ADJ amod
Мансийского ADJ amod
автономного ADJ amod
округа NOUN nmod
— PUNCT punct
Югры PROPN parataxis
Наталья PROPN appos
Комарова PROPN flat:name
назначила VERB ROOT
на ADP case
должность NOUN obl
своего DET det
заместителя NOUN nmod
Дмитрия PROPN appos
Шаповала PROPN flat:name
; PUNCT punct
в ADP case
его DET det
ведении NOUN obl
будут AUX aux
находиться VERB conj
окружные ADJ amod
департаменты NOUN nsubj
дорожного ADJ amod
хозяйства NOUN nmod
и CCONJ cc
транспорта NOUN conj
, PUNCT punct
строительства NOUN conj
, PUNCT punct
ЖКХ PROPN conj
и CCONJ cc
энергетики NOUN conj
, PUNCT punct
сообщает VERB parataxis
пресс NOUN nsubj
- NOUN nsubj
служба NOUN nsubj
губернатора NOUN nmod
. PUNCT punct
" PUNCT punct
Новым ADJ amod
заместителем NOUN xcomp
главы NOUN nmod
региона NOUN nmod
с ADP case
21 ADJ obl
июня NOUN flat
2013 ADJ amod
года NOUN nmod
назначен VERB ROOT
Дмитрий PROPN nsubj:pass
Викторович PROPN flat:name
Шаповал PROPN flat:name
, PUNCT punct
который PRON nsubj
будет AUX aux
отвечать VERB acl:relcl
за ADP case
окружные VERB amod
департаменты NOUN obl
дорожного ADJ amod
хозяйства NOUN nmod
и CCONJ cc
транспорта NOUN conj
, PUNCT punct
строительства NOUN conj
, PUNCT punct
ЖКХ PROPN conj
и CCONJ cc
энергетики NOUN conj
, PUNCT punct
гражданской ADJ amod
защиты NOUN conj
населения NOUN nmod
, PUNCT punct
а CCONJ cc
также ADV fixed
служба NOUN conj
государственного ADJ amod
надзора NOUN nmod
за ADP case
техническим ADJ amod
состоянием NOUN nmod
самоходных ADJ amod
машин NOUN nmod
и CCONJ cc
других ADJ amod
видов NOUN conj
техники NOUN nmod
. PUNCT punct
Ранее ADV advmod
этот DET det
пост NOUN obj
в ADP case
правительстве NOUN obl
Югры PROPN nmod
занимал VERB ROOT
Валентин PROPN nsubj
Грипас PROPN flat:name
, PUNCT punct
который PRON nsubj:pass
20 ADJ obl
июня NOUN flat
уволен VERB acl:relcl
по ADP case
собственному ADJ amod
желанию NOUN obl
" PUNCT punct
, PUNCT punct
— PUNCT punct
говорится VERB parataxis
в ADP case
сообщении NOUN obl
. PUNCT punct
Дмитрий PROPN nsubj
Шаповал PROPN appos
родился VERB ROOT
в ADP case
Магнитогорске PROPN obl
в ADP case
1979 ADJ amod
году NOUN obl
. PUNCT punct
Окончил VERB ROOT
Магнитогорский ADJ amod
государственный ADJ amod
технический ADJ amod
университет NOUN obj
им. NOUN nmod
Носова PROPN nmod
, PUNCT punct
защитил VERB conj
диссертацию NOUN obj
по ADP case
специальности NOUN nmod
" PUNCT punct
строительные ADJ amod
конструкции NOUN appos
зданий NOUN nmod
и CCONJ cc
сооружений NOUN conj
" PUNCT punct
. PUNCT punct
В ADP case
2011 ADJ amod
году NOUN obl
назначен VERB ROOT
заместителем NOUN xcomp
директора NOUN nmod
департамента NOUN nmod
строительства NOUN nmod
, PUNCT punct
энергетики NOUN conj
и CCONJ cc
жилищно ADJ amod
- ADJ amod
коммунального ADJ amod
комплекса NOUN conj
Югры PROPN nmod
, PUNCT punct
в ADP case
котором PRON obl
курировал VERB acl:relcl
вопросы NOUN obj
строительства NOUN nmod
, PUNCT punct
после ADP case
чего PRON obl
возглавил VERB parataxis
департамент NOUN nsubj
архитектуры NOUN nmod
, PUNCT punct
строительства NOUN conj
и CCONJ cc
градостроительной ADJ amod
политики NOUN conj
министерства NOUN nmod
регионального ADJ amod
развития NOUN nmod
Российской ADJ amod
Федерации PROPN nmod
и CCONJ cc
проработал VERB conj
в ADP case
этой DET det
должности NOUN obl
до ADP case
2012 ADJ amod
года NOUN obl
. PUNCT punct
С ADP case
2012 ADJ obl
по ADP case
2013 ADJ amod
год NOUN obl
занимал VERB ROOT
пост NOUN obj
министра NOUN nmod
строительства NOUN nmod
и CCONJ cc
архитектуры NOUN conj
Пермского ADJ amod
края NOUN nmod
. PUNCT punct
В ADP case
2013 ADJ amod
году NOUN obl
был AUX aux:pass
назначен VERB ROOT
директором NOUN xcomp
департамента NOUN nmod
взаимодействия NOUN nmod
с ADP case
органами NOUN nmod
государственной ADJ amod
власти NOUN nmod
Национального ADJ amod
объединения NOUN nmod
строителей NOUN nmod
. PUNCT punct

DeepPavlov

In [47]:
!python -m venv env
!.\env\Scripts\activate.bat
!pip install deeppavlov
!python -m deeppavlov install squad_bert
!python -m deeppavlov install ner_ontonotes

import deeppavlov
from deeppavlov import configs, build_model
deeppavlov_ner = build_model(configs.ner.ner_rus, download=True)
rus_document = "Нью-Йорк, США, 30 апреля 2020, 01:01 — REGNUM В администрации президента США Дональда Трампа планируют пройти все этапы создания вакцины от коронавируса в ускоренном темпе и выпустить 100 млн доз до конца 2020 года, передаёт агентство Bloomberg со ссылкой на осведомлённые источники"
deeppavlov_ner([rus_document])

The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt install python3.10-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: /content/env/bin/python3

/bin/bash: line 1: .envScriptsactivate.bat: command not found
Requirement already satisfied: deeppavlov in /usr/local/lib/python3.10/dist-packages (1.4.0)
Requirement already satisfied: fastapi<=0.89.1,>=0.47.0 in /usr/local/lib/python3.10/dist-packages (from deeppavlov) (0.89.1)
Requirement already satisfied: filelock<3.10.0,>=3.0.0 in /usr/local/lib/python3.10/dist-packages (from deeppavlov) (3.9.1)
Requirement already satisfied: nltk<3.10.0,>=3.2.4 in /usr/local/lib/python3.10/dist-packages (from deeppavlov) (3.8.1)
Requirement already satisfied: numpy<1.24 in /usr/local/lib/python3.10/dist-packages (from deeppavlov) (1.23.5)
Requirement already satisfied: pandas<1.6.0,>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from deeppavlov) (1.5.3)
Requirement already satisfied: prometheus-client<=1.16.0,>=0.13.0 in /usr/local/lib/python3.10/dist-packages (from deeppavlov) (0.19.0)
Requirement already satisfied: pydantic<2 in /usr/local/lib/python3.10/dist-packages (from deeppavlov) (1.10.13)
Requirement already satisfied: pybind11==2.10.3 in /usr/local/lib/python3.10/dist-packages (from deeppavlov) (2.10.3)
Requirement already satisfied: requests<3.0.0,>=2.19.0 in /usr/local/lib/python3.10/dist-packages (from deeppavlov) (2.31.0)
Requirement already satisfied: scikit-learn<1.1.0,>=0.24 in /usr/local/lib/python3.10/dist-packages (from deeppavlov) (1.0.2)
Requirement already satisfied: tqdm<4.65.0,>=4.42.0 in /usr/local/lib/python3.10/dist-packages (from deeppavlov) (4.64.1)
Requirement already satisfied: uvicorn<0.19.0,>=0.13.0 in /usr/local/lib/python3.10/dist-packages (from deeppavlov) (0.18.3)
Requirement already satisfied: wheel in /usr/local/lib/python3.10/dist-packages (from deeppavlov) (0.42.0)
Requirement already satisfied: scipy==1.10.0 in /usr/local/lib/python3.10/dist-packages (from deeppavlov) (1.10.0)
Requirement already satisfied: starlette==0.22.0 in /usr/local/lib/python3.10/dist-packages (from fastapi<=0.89.1,>=0.47.0->deeppavlov) (0.22.0)
Requirement already satisfied: anyio<5,>=3.4.0 in /usr/local/lib/python3.10/dist-packages (from starlette==0.22.0->fastapi<=0.89.1,>=0.47.0->deeppavlov) (3.7.1)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from nltk<3.10.0,>=3.2.4->deeppavlov) (8.1.7)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from nltk<3.10.0,>=3.2.4->deeppavlov) (1.3.2)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.10/dist-packages (from nltk<3.10.0,>=3.2.4->deeppavlov) (2023.6.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas<1.6.0,>=1.0.0->deeppavlov) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas<1.6.0,>=1.0.0->deeppavlov) (2023.3.post1)
Requirement already satisfied: typing-extensions>=4.2.0 in /usr/local/lib/python3.10/dist-packages (from pydantic<2->deeppavlov) (4.5.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.19.0->deeppavlov) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.19.0->deeppavlov) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.19.0->deeppavlov) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.19.0->deeppavlov) (2023.11.17)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn<1.1.0,>=0.24->deeppavlov) (3.2.0)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.10/dist-packages (from uvicorn<0.19.0,>=0.13.0->deeppavlov) (0.14.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas<1.6.0,>=1.0.0->deeppavlov) (1.16.0)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.10/dist-packages (from anyio<5,>=3.4.0->starlette==0.22.0->fastapi<=0.89.1,>=0.47.0->deeppavlov) (1.3.0)
Requirement already satisfied: exceptiongroup in /usr/local/lib/python3.10/dist-packages (from anyio<5,>=3.4.0->starlette==0.22.0->fastapi<=0.89.1,>=0.47.0->deeppavlov) (1.2.0)
Requirement already satisfied: torch<1.14.0,>=1.6.0 in /usr/local/lib/python3.10/dist-packages (1.13.1)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.10/dist-packages (from torch<1.14.0,>=1.6.0) (4.5.0)
Requirement already satisfied: nvidia-cuda-runtime-cu11==11.7.99 in /usr/local/lib/python3.10/dist-packages (from torch<1.14.0,>=1.6.0) (11.7.99)
Requirement already satisfied: nvidia-cudnn-cu11==8.5.0.96 in /usr/local/lib/python3.10/dist-packages (from torch<1.14.0,>=1.6.0) (8.5.0.96)
Requirement already satisfied: nvidia-cublas-cu11==11.10.3.66 in /usr/local/lib/python3.10/dist-packages (from torch<1.14.0,>=1.6.0) (11.10.3.66)
Requirement already satisfied: nvidia-cuda-nvrtc-cu11==11.7.99 in /usr/local/lib/python3.10/dist-packages (from torch<1.14.0,>=1.6.0) (11.7.99)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from nvidia-cublas-cu11==11.10.3.66->torch<1.14.0,>=1.6.0) (67.7.2)
Requirement already satisfied: wheel in /usr/local/lib/python3.10/dist-packages (from nvidia-cublas-cu11==11.10.3.66->torch<1.14.0,>=1.6.0) (0.42.0)
Ignoring transformers: markers 'python_version < "3.8"' don't match your environment
Requirement already satisfied: transformers==4.30.0 in /usr/local/lib/python3.10/dist-packages (4.30.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from transformers==4.30.0) (3.9.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.14.1 in /usr/local/lib/python3.10/dist-packages (from transformers==4.30.0) (0.19.4)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from transformers==4.30.0) (1.23.5)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from transformers==4.30.0) (23.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers==4.30.0) (6.0.1)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers==4.30.0) (2023.6.3)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from transformers==4.30.0) (2.31.0)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in /usr/local/lib/python3.10/dist-packages (from transformers==4.30.0) (0.13.3)
Requirement already satisfied: safetensors>=0.3.1 in /usr/local/lib/python3.10/dist-packages (from transformers==4.30.0) (0.4.1)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.10/dist-packages (from transformers==4.30.0) (4.64.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.14.1->transformers==4.30.0) (2023.6.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.14.1->transformers==4.30.0) (4.5.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->transformers==4.30.0) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->transformers==4.30.0) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->transformers==4.30.0) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->transformers==4.30.0) (2023.11.17)
2023-12-04 20:07:46.601 WARNING in 'deeppavlov.core.common.file'['file'] at line 39:

################################################################################
# The model 'ner_ontonotes' has been removed from the DeepPavlov configs.
# The model 'ner_ontonotes_bert' is used instead.
# To disable this message please switch to 'ner_ontonotes_bert'.
# Automatic name resolving will be disabled in the deeppavlov 1.2.0,
# and if you try to use 'ner_ontonotes' you will get an ERROR.
################################################################################

Ignoring transformers: markers 'python_version < "3.8"' don't match your environment
Requirement already satisfied: transformers==4.30.0 in /usr/local/lib/python3.10/dist-packages (4.30.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from transformers==4.30.0) (3.9.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.14.1 in /usr/local/lib/python3.10/dist-packages (from transformers==4.30.0) (0.19.4)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from transformers==4.30.0) (1.23.5)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from transformers==4.30.0) (23.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers==4.30.0) (6.0.1)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers==4.30.0) (2023.6.3)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from transformers==4.30.0) (2.31.0)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in /usr/local/lib/python3.10/dist-packages (from transformers==4.30.0) (0.13.3)
Requirement already satisfied: safetensors>=0.3.1 in /usr/local/lib/python3.10/dist-packages (from transformers==4.30.0) (0.4.1)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.10/dist-packages (from transformers==4.30.0) (4.64.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.14.1->transformers==4.30.0) (2023.6.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.14.1->transformers==4.30.0) (4.5.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->transformers==4.30.0) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->transformers==4.30.0) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->transformers==4.30.0) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->transformers==4.30.0) (2023.11.17)
Requirement already satisfied: pytorch-crf==0.7.* in /usr/local/lib/python3.10/dist-packages (0.7.2)
Requirement already satisfied: torch<1.14.0,>=1.6.0 in /usr/local/lib/python3.10/dist-packages (1.13.1)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.10/dist-packages (from torch<1.14.0,>=1.6.0) (4.5.0)
Requirement already satisfied: nvidia-cuda-runtime-cu11==11.7.99 in /usr/local/lib/python3.10/dist-packages (from torch<1.14.0,>=1.6.0) (11.7.99)
Requirement already satisfied: nvidia-cudnn-cu11==8.5.0.96 in /usr/local/lib/python3.10/dist-packages (from torch<1.14.0,>=1.6.0) (8.5.0.96)
Requirement already satisfied: nvidia-cublas-cu11==11.10.3.66 in /usr/local/lib/python3.10/dist-packages (from torch<1.14.0,>=1.6.0) (11.10.3.66)
Requirement already satisfied: nvidia-cuda-nvrtc-cu11==11.7.99 in /usr/local/lib/python3.10/dist-packages (from torch<1.14.0,>=1.6.0) (11.7.99)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from nvidia-cublas-cu11==11.10.3.66->torch<1.14.0,>=1.6.0) (67.7.2)
Requirement already satisfied: wheel in /usr/local/lib/python3.10/dist-packages (from nvidia-cublas-cu11==11.10.3.66->torch<1.14.0,>=1.6.0) (0.42.0)

AttributeError: ignored

Не получается установить deeppavlov.

Самописный NER.

In [50]:
def get_classification_report(y_test_true, y_test_pred):
    print(classification_report(y_test_true, y_test_pred))

    print('CONFUSION MATRIX\n')
    print(pd.crosstab(y_test_true, y_test_pred))

Воспользуемся размеченным корпусом текстов.

In [51]:
records = load_ne5('Collection5/')
next(records)

Ne5Markup(
    id='1016',
    text='Губернатор Югры назначила нового заместителя по строительству и ЖКХ\r\n\r\n\r\nГубернатор Ханты-Мансийского автономного округа - Югры Наталья Комарова назначила на должность своего заместителя Дмитрия Шаповала; в его ведении будут находиться окружные департаменты дорожного хозяйства и транспорта, строительства, ЖКХ и энергетики.\r\nГубернатор Ханты-Мансийского автономного округа – Югры Наталья Комарова. Архив\r\n\r\n Губернатор Ханты-Мансийского автономного округа — Югры Наталья Комарова назначила на должность своего заместителя Дмитрия Шаповала; в его ведении будут находиться окружные департаменты дорожного хозяйства и транспорта, строительства, ЖКХ и энергетики, сообщает пресс-служба губернатора.\r\n\r\n"Новым заместителем главы региона с 21 июня 2013 года назначен Дмитрий Викторович Шаповал, который будет отвечать за окружные департаменты дорожного хозяйства и транспорта, строительства, ЖКХ и энергетики, гражданской защиты населения, а также служба государственного надзора за техническим состоянием самоходных машин и других видов техники. Ранее этот пост в правительстве Югры занимал Валентин Грипас, который 20 июня уволен по собственному желанию", — говорится в сообщении.\r\n\r\nДмитрий Шаповал родился в Магнитогорске в 1979 году. Окончил Магнитогорский государственный технический университет им. Носова, защитил диссертацию по специальности "строительные конструкции зданий и сооружений".\r\n\r\nВ 2011 году назначен заместителем директора департамента строительства, энергетики и жилищно-коммунального комплекса Югры, в котором курировал вопросы строительства, после чего возглавил департамент архитектуры, строительства и градостроительной политики министерства регионального развития Российской Федерации и проработал в этой должности до 2012 года.\r\n\r\nС 2012 по 2013 год занимал пост министра строительства и архитектуры Пермского края. В 2013 году был назначен директором департамента взаимодействия с органами государственной власти Национального объединения строителей.',
    spans=[Ne5Span(
         index='T1',
         type='LOC',
         start=11,
         stop=15,
         text='Югры'
     ),
     Ne5Span(
         index='T2',
         type='LOC',
         start=84,
         stop=127,
         text='Ханты-Мансийского автономного округа - Югры'
     ),
     Ne5Span(
         index='T3',
         type='PER',
         start=128,
         stop=144,
         text='Наталья Комарова'
     ),
     Ne5Span(
         index='T4',
         type='PER',
         start=187,
         stop=203,
         text='Дмитрия Шаповала'
     ),
     Ne5Span(
         index='T5',
         type='LOC',
         start=337,
         stop=380,
         text='Ханты-Мансийского автономного округа – Югры'
     ),
     Ne5Span(
         index='T6',
         type='PER',
         start=381,
         stop=397,
         text='Наталья Комарова'
     ),
     Ne5Span(
         index='T7',
         type='LOC',
         start=420,
         stop=463,
         text='Ханты-Мансийского автономного округа — Югры'
     ),
     Ne5Span(
         index='T8',
         type='PER',
         start=464,
         stop=480,
         text='Наталья Комарова'
     ),
     Ne5Span(
         index='T9',
         type='PER',
         start=523,
         stop=539,
         text='Дмитрия Шаповала'
     ),
     Ne5Span(
         index='T10',
         type='PER',
         start=762,
         stop=788,
         text='Дмитрий Викторович Шаповал'
     ),
     Ne5Span(
         index='T11',
         type='LOC',
         start=1074,
         stop=1078,
         text='Югры'
     ),
     Ne5Span(
         index='T12',
         type='PER',
         start=1087,
         stop=1102,
         text='Валентин Грипас'
     ),
     Ne5Span(
         index='T13',
         type='PER',
         start=1181,
         stop=1196,
         text='Дмитрий Шаповал'
     ),
     Ne5Span(
         index='T14',
         type='LOC',
         start=1207,
         stop=1220,
         text='Магнитогорске'
     ),
     Ne5Span(
         index='T15',
         type='ORG',
         start=1242,
         stop=1307,
         text='Магнитогорский государственный технический университет им. Носова'
     ),
     Ne5Span(
         index='T16',
         type='LOC',
         start=1514,
         stop=1518,
         text='Югры'
     ),
     Ne5Span(
         index='T17',
         type='GEOPOLIT',
         start=1688,
         stop=1708,
         text='Российской Федерации'
     ),
     Ne5Span(
         index='T18',
         type='LOC',
         start=1825,
         stop=1839,
         text='Пермского края'
     )]
)

In [52]:
words_docs = []
for ix, rec in enumerate(records):
    words = []
    for token in tokenize(rec.text):
        type_ent = 'OUT'
        for ent in rec.spans:
            if (token.start >= ent.start) and (token.stop <= ent.stop):
                type_ent = ent.type
                break
        words.append([token.text, type_ent])
    words_docs.extend(words)

In [53]:
df_words = pd.DataFrame(words_docs, columns=['word', 'tag'])

In [54]:
df_words['tag'].value_counts()

OUT         218990
PER          21183
ORG          13644
LOC           4547
GEOPOLIT      4354
MEDIA         2482
Name: tag, dtype: int64

In [55]:
df_words.head()

                 word  tag
0           Директора  OUT
1                 МВФ  ORG
2           назначили  OUT
3            арбитром  OUT
4  межгосударственных  OUT

In [57]:
train_x, valid_x, train_y, valid_y = model_selection.train_test_split(df_words['word'], df_words['tag'])

Закодируем целевую переменную.

In [58]:
encoder = preprocessing.LabelEncoder()
train_y = encoder.fit_transform(train_y)
valid_y = encoder.fit_transform(valid_y)

Посмотрим на классы.

In [59]:
encoder.classes_

array(['GEOPOLIT', 'LOC', 'MEDIA', 'ORG', 'OUT', 'PER'], dtype=object)

In [60]:
train_x.apply(len).max(axis=0)

55

In [61]:
valid_x

228773    кандидатуру
174558              М
108780     обеспечить
35484               "
29653       прокуроре
             ...
29297               ,
104583    спутниковые
103396           года
188866          также
237984       пообещал
Name: word, Length: 66300, dtype: object

In [62]:
train_data = tf.data.Dataset.from_tensor_slices((train_x, train_y))
valid_data = tf.data.Dataset.from_tensor_slices((valid_x, valid_y))

train_data = train_data.batch(16)
valid_data = valid_data.batch(16)

In [63]:
AUTOTUNE = tf.data.experimental.AUTOTUNE

train_data = train_data.cache().prefetch(buffer_size=AUTOTUNE)
valid_data = valid_data.cache().prefetch(buffer_size=AUTOTUNE)

In [64]:
def custom_standardization(input_data):
    # Здесь может быть предобработка текста
    return input_data

vocab_size = 30000
seq_len = 10

vectorize_layer = TextVectorization(
                            standardize=custom_standardization,
                            max_tokens=vocab_size,
                            output_mode='int',
                            #ngrams=(1, 3),
                            output_sequence_length=seq_len)

# Make a text-only dataset (no labels) and call adapt to build the vocabulary.
text_data = train_data.map(lambda x, y: x)
vectorize_layer.adapt(text_data)

In [65]:
len(vectorize_layer.get_vocabulary())

29872

In [66]:
embedding_dim = 64

class modelNER(tf.keras.Model):
    def __init__(self):
        super(modelNER, self).__init__()
        self.emb = Embedding(vocab_size, embedding_dim)
        self.gPool = GlobalMaxPooling1D()
        self.fc1 = Dense(300, activation='relu')
        self.fc2 = Dense(50, activation='relu')
        self.fc3 = Dense(6, activation='softmax') # [OUT, PER, ORG, LOC, GEOPOLIT, MEDIA]

    def call(self, x):
        x = vectorize_layer(x)
        x = self.emb(x)
        pool_x = self.gPool(x)

        fc_x = self.fc1(pool_x)
        fc_x = self.fc2(fc_x)

        concat_x = tf.concat([pool_x, fc_x], axis=1)
        prob = self.fc3(concat_x)
        return prob

In [67]:
mmodel = modelNER()

In [68]:
mmodel.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(),
              metrics=['accuracy'])

In [69]:
mmodel.fit( train_data,
            validation_data=valid_data,
            epochs=3)

Epoch 1/3
12432/12432 [==============================] - 553s 44ms/step - loss: 0.2975 - accuracy: 0.9127 - val_loss: 0.2087 - val_accuracy: 0.9370
Epoch 2/3
12432/12432 [==============================] - 498s 40ms/step - loss: 0.1264 - accuracy: 0.9624 - val_loss: 0.2074 - val_accuracy: 0.9415
Epoch 3/3
12432/12432 [==============================] - 484s 39ms/step - loss: 0.1099 - accuracy: 0.9655 - val_loss: 0.2171 - val_accuracy: 0.9420

In [70]:
pred_y = mmodel.predict(valid_x)
y_pred_classes = np.argmax(pred_y,axis=1)

2072/2072 [==============================] - 9s 4ms/step

In [71]:
f1 = f1_score(valid_y, y_pred_classes, average= 'weighted')
f1

0.937412243261704

In [72]:
print(f'Classes: {encoder.classes_}\r\n')

get_classification_report(valid_y, y_pred_classes)

Classes: ['GEOPOLIT' 'LOC' 'MEDIA' 'ORG' 'OUT' 'PER']

              precision    recall  f1-score   support

           0       0.89      0.90      0.89      1119
           1       0.86      0.79      0.83      1145
           2       0.94      0.76      0.84       630
           3       0.91      0.55      0.68      3411
           4       0.94      0.99      0.97     54628
           5       0.97      0.72      0.83      5367

    accuracy                           0.94     66300
   macro avg       0.92      0.79      0.84     66300
weighted avg       0.94      0.94      0.94     66300

CONFUSION MATRIX

col_0     0    1    2     3      4     5
row_0
0      1005   20    1    28     64     1
1        15  910    2    24    192     2
2         1    2  481    13    131     2
3       105   32   19  1867   1372    16
4         5   95   10   119  54320    79
5         0    1    1     3   1491  3871

Обучим нейронную сеть на биграммах и триграммах.

In [73]:
def custom_standardization(input_data):
    # Здесь может быть предобработка текста.
    return input_data

vocab_size = 30000
seq_len = 10

vectorize_layer = TextVectorization(
                            standardize=custom_standardization,
                            max_tokens=vocab_size,
                            output_mode='int',
                            ngrams=(1, 3),
                            output_sequence_length=seq_len)

# Make a text-only dataset (no labels) and call adapt to build the vocabulary.
text_data = train_data.map(lambda x, y: x)
vectorize_layer.adapt(text_data)

In [74]:
mmodel = modelNER()

In [75]:
mmodel.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(),
              metrics=['accuracy'])

In [76]:
mmodel.fit( train_data,
            validation_data=valid_data,
            epochs=3)

Epoch 1/3
12432/12432 [==============================] - 501s 40ms/step - loss: 0.3010 - accuracy: 0.9122 - val_loss: 0.2082 - val_accuracy: 0.9372
Epoch 2/3
12432/12432 [==============================] - 499s 40ms/step - loss: 0.1279 - accuracy: 0.9615 - val_loss: 0.2759 - val_accuracy: 0.8947
Epoch 3/3
12432/12432 [==============================] - 466s 37ms/step - loss: 0.1104 - accuracy: 0.9654 - val_loss: 0.2148 - val_accuracy: 0.9408

In [80]:
pred_y = mmodel.predict(valid_x)
y_pred_classes = np.argmax(pred_y,axis=1)

2072/2072 [==============================] - 9s 4ms/step

In [78]:
f1 = f1_score(valid_y, y_pred_classes, average= 'weighted')
f1

0.9359607765383628

In [79]:
print(f'Classes: {encoder.classes_}\r\n')

get_classification_report(valid_y, y_pred_classes)

Classes: ['GEOPOLIT' 'LOC' 'MEDIA' 'ORG' 'OUT' 'PER']

              precision    recall  f1-score   support

           0       0.89      0.90      0.89      1119
           1       0.85      0.79      0.82      1145
           2       0.93      0.76      0.84       630
           3       0.90      0.53      0.67      3411
           4       0.94      0.99      0.97     54628
           5       0.97      0.72      0.83      5367

    accuracy                           0.94     66300
   macro avg       0.91      0.78      0.84     66300
weighted avg       0.94      0.94      0.94     66300

CONFUSION MATRIX

col_0     0    1    2     3      4     5
row_0
0      1003   21    3    27     64     1
1        17  910    0    21    195     2
2         1    2  481    13    132     1
3       100   37   19  1814   1424    17
4         5   99   12   139  54294    79
5         0    2    1     3   1491  3870

Результьат выше у сети, которая обучалась на N-граммах.